Further build script improvements from review
Signed-off-by: iliana destroyer of worlds <iweller@amazon.com>

diff --git a/bin/spec2pkg b/bin/spec2pkg
--- a/bin/spec2pkg
+++ b/bin/spec2pkg
@@ -23,8 +23,8 @@ RPMS="${RPMS%"${RPMS##*[![:space:]]}"}"
 
 # Collect file-based targets needed as inputs of a package build.
 SOURCE_LINES="$("${RPMSPEC[@]}" --parse "${SPEC}" | awk '/^Source/ {print $NF}')"
-SOURCE_URLS="$(awk '$0 ~ "^https?://" {print}' <<<"$SOURCE_LINES")"
-SOURCES="$(awk -v pkg="${PKG}" -F / '{printf "packages/%s/%s ",pkg,$NF}' <<<"$SOURCE_LINES")"
+SOURCE_URLS="$(awk '$0 ~ "^https?://" {print}' <<<"${SOURCE_LINES}")"
+SOURCES="$(awk -v pkg="${PKG}" -F / '{printf "packages/%s/%s ",pkg,$NF}' <<<"${SOURCE_LINES}")"
 SOURCES="${SOURCES%"${SOURCES##*[![:space:]]}"}"
 
 PATCHES="$("${RPMSPEC[@]}" --parse "${SPEC}" \
@@ -42,16 +42,16 @@ echo -e ".INTERMEDIATE: build-${PKG}-${ARCH}\n"
 echo "build-${PKG}-${ARCH} : ${SPEC} ${SOURCES} ${PATCHES} ${BUILDREQUIRES}"
 echo -e "\t\$(call build_rpm,$PKG,${ARCH},\$^)\n"
 
-for URL in ${SOURCE_URLS}; do
-    FILENAME="${URL##*/}"
-    if grep -q '^https://crates.io/api/v1/crates/[^/]\+/[^/]\+/download' <<<"$URL"; then
-        CHECKSUM="$(awk -F / '{print $1}' <<<"${URL##*#}")"
+for url in ${SOURCE_URLS}; do
+    FILENAME="${url##*/}"
+    if grep -q '^https://crates.io/api/v1/crates/[^/]\+/[^/]\+/download' <<<"$url"; then
+        CHECKSUM="$(awk -F / '{print $1}' <<<"${url##*#}")"
     elif [[ -f "packages/${PKG}/sources" ]]; then
         CHECKSUM="$(awk -v filename="(${FILENAME})" '$2 == filename {print $4}' "packages/${PKG}/sources")"
     else
-        echo -e "# download rule for packages/${PKG}/${FILENAME} couldn't be generated\n"
-        continue
+        echo -e "# download rule for packages/${PKG}/${FILENAME} couldn't be generated\n" 1>&2
+        exit 1
     fi
     echo "packages/${PKG}/${FILENAME} :"
-    echo -e "\t@bin/fetch-upstream \"${URL}\" \"packages/${PKG}/${FILENAME}\" \"${CHECKSUM}\"\n"
+    echo -e "\t@\$(FETCH_UPSTREAM) \"${url}\" \"packages/${PKG}/${FILENAME}\" \"${CHECKSUM}\"\n"
 done
