build: use SDK container for build image
Signed-off-by: Ben Cressey <bcressey@amazon.com>

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -15,6 +15,8 @@ DOCKER_BUILDKIT = "1"
 
 [env.development]
 IMAGE = "aws-k8s"
+# Defined here to allow us to override ${BUILDSYS_ARCH} on the command line.
+BUILDSYS_SDK_IMAGE = "thar/sdk-${BUILDSYS_ARCH}:0.0.1"
 # Permit pulling directly Upstream URLs when lookaside cache results in MISSes.
 BUILDSYS_ALLOW_UPSTREAM_SOURCE_URL = "true"
 # Extra flags used when spawning containers.
@@ -28,11 +30,38 @@ script = [
 '''
 mkdir -p ${BUILDSYS_OUTPUT_DIR}
 mkdir -p ${GO_MOD_CACHE}
+
+for cmd in bash curl docker gunzip ; do
+  if ! command -v ${cmd} >/dev/null 2>&1 ; then
+    echo "required program '${cmd}' not found" >&2
+    exit 1
+  fi
+done
 '''
 ]
 
 [tasks.fetch]
-dependencies = ["fetch-workspaces", "fetch-vendored"]
+dependencies = [
+  "fetch-sdk",
+  "fetch-workspaces",
+  "fetch-vendored",
+]
+
+[tasks.fetch-sdk]
+dependencies = ["setup"]
+script_runner = "bash"
+script = [
+'''
+set -o pipefail
+if ! docker image inspect ${BUILDSYS_SDK_IMAGE} >/dev/null 2>&1 ; then
+  if ! curl https://thar-upstream-lookaside-cache.s3.us-west-2.amazonaws.com/${BUILDSYS_SDK_IMAGE}.tar.gz \
+       | gunzip | docker load ; then
+    echo "failed to load '${BUILDSYS_SDK_IMAGE}'" >&2
+    exit 1
+  fi
+fi
+'''
+]
 
 [tasks.fetch-workspaces]
 dependencies = ["setup"]
