relauto: lock versions of cargo binary deps

diff --git a/tools/infra/env/bin/setup-rust-builder b/tools/infra/env/bin/setup-rust-builder
--- a/tools/infra/env/bin/setup-rust-builder
+++ b/tools/infra/env/bin/setup-rust-builder
@@ -40,9 +40,10 @@ configure_color_output() {
 }
 
 cargo_dep() {
-    cargo_install_package="$1"
-    if ! cargo install --force "$cargo_install_package"; then
-        logmsg "ERROR: could not install cargo packaged dependency: $cargo_install_package"
+    cargo_install_package="$@"
+    logmsg "INFO: installing cargo dep with 'cargo install $cargo_install_package'"
+    if ! cargo install --force $cargo_install_package; then
+        logmsg "ERROR: failed to install dep with 'cargo install $cargo_install_package'"
         exit 1
     fi
 }
@@ -65,8 +66,8 @@ configure_color_output
 install_rust_toolchain
 
 # Install build tooling dependencies
-cargo_dep cargo-make
-cargo_dep cargo-deny
+cargo_dep --version 0.23.0 cargo-make
+cargo_dep --version 0.3.0  cargo-deny
 
 unset -f configure_color_output
 unset -f install_rust_toolchain
